apiVersion: realm.keycloak.m.crossplane.io/v1alpha1
kind: KeystoreRsa
metadata:
  annotations:
    meta.upbound.io/example-id: realm/v1alpha1/keystorersa
  labels:
    testing.upbound.io/example-name: keystore_rsa
  name: keystore-rsa
  namespace: upbound-system
spec:
  forProvider:
    active: true
    algorithm: RS256
    certificateSecretRef:
      key: example-key
      name: example-secret
    enabled: true
    keystore_size: 2048
    name: my-rsa-key
    priority: 100
    privateKeySecretRef:
      key: example-key
      name: example-secret
    providerId: rsa
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: realm.keycloak.m.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: realm/v1alpha1/keystorersa
  labels:
    testing.upbound.io/example-name: realm
  name: realm
  namespace: upbound-system
spec:
  forProvider:
    realm: my-realm
