apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientDefaultScopes
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientdefaultscopes
  labels:
    testing.upbound.io/example-name: client_default_scopes
  name: client-default-scopes
spec:
  forProvider:
    clientIdSelector:
      matchLabels:
        testing.upbound.io/example-name: client
    defaultScopes:
    - profile
    - email
    - roles
    - web-origins
    - ${keycloak_openid_client_scope.client_scope.name}
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientdefaultscopes
  labels:
    testing.upbound.io/example-name: client
  name: client
spec:
  forProvider:
    accessType: CONFIDENTIAL
    clientIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientScope
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientdefaultscopes
  labels:
    testing.upbound.io/example-name: client_scope
  name: client-scope
spec:
  forProvider:
    name: test-client-scope
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientdefaultscopes
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm
