apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientClientPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientclientpolicy
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    clientsRefs:
    - name: client1
    - name: client2
    decisionStrategy: UNANIMOUS
    logic: POSITIVE
    name: client_policy
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    resourceServerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: openidclient.keycloak.crossplane.io/v1alpha2
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientclientpolicy
  labels:
    testing.upbound.io/example-name: client1
  name: client1
spec:
  forProvider:
    accessType: CONFIDENTIAL
    clientId: client1
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    serviceAccountsEnabled: true

---

apiVersion: openidclient.keycloak.crossplane.io/v1alpha2
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientclientpolicy
  labels:
    testing.upbound.io/example-name: client2
  name: client2
spec:
  forProvider:
    accessType: CONFIDENTIAL
    clientId: client2
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    serviceAccountsEnabled: true

---

apiVersion: openidclient.keycloak.crossplane.io/v1alpha2
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientclientpolicy
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    accessType: CONFIDENTIAL
    authorization:
    - policyEnforcementMode: ENFORCING
    clientId: client_id
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    serviceAccountsEnabled: true

---

apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientclientpolicy
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm
