apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientScope
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientscope
  labels:
    testing.upbound.io/example-name: openid_client_scope
  name: openid-client-scope
spec:
  forProvider:
    description: When requested, this scope will map a user's group memberships to
      a claim
    guiOrder: 1
    includeInTokenScope: true
    name: groups
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientscope
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm
