apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientAuthorizationResource
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientauthorizationresource
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    attributes:
      key1: value1,value2
      key2: value3
    displayName: My Resource
    name: my_resource
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    resourceServerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    scopes:
    - ${keycloak_openid_client_authorization_scope.read_scope.name}
    - ${keycloak_openid_client_authorization_scope.write_scope.name}
    type: http://example.com/resource-type
    uris:
    - /api/resource/*
    - /api/resource/**

---

apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientauthorizationresource
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    accessType: CONFIDENTIAL
    authorization:
    - policyEnforcementMode: ENFORCING
    clientId: client_id
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    serviceAccountsEnabled: true

---

apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientauthorizationresource
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm
