apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientAggregatePolicy
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientaggregatepolicy
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    decisionStrategy: AFFIRMATIVE
    logic: POSITIVE
    name: aggregate_policy
    policies:
    - ${keycloak_openid_client_role_policy.role_policy.id}
    - ${keycloak_openid_client_user_policy.user_policy.id}
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    resourceServerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientaggregatepolicy
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    accessType: CONFIDENTIAL
    authorization:
    - policyEnforcementMode: ENFORCING
    clientId: client_id
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    serviceAccountsEnabled: true

---

apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientRolePolicy
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientaggregatepolicy
  labels:
    testing.upbound.io/example-name: role_policy
  name: role-policy
spec:
  forProvider:
    decisionStrategy: UNANIMOUS
    logic: POSITIVE
    name: role_policy
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    resourceServerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    role:
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: test
      required: true

---

apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientUserPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientaggregatepolicy
  labels:
    testing.upbound.io/example-name: user_policy
  name: user-policy
spec:
  forProvider:
    decisionStrategy: UNANIMOUS
    logic: POSITIVE
    name: user_policy
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    resourceServerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    usersRefs:
    - name: test

---

apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientaggregatepolicy
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm
