apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: KeystoreJavaKeystore
metadata:
  annotations:
    meta.upbound.io/example-id: realm/v1alpha1/keystorejavakeystore
  labels:
    testing.upbound.io/example-name: java_keystore
  name: java-keystore
spec:
  forProvider:
    active: true
    algorithm: RS256
    enabled: true
    keyAlias: <alias for the private key>
    keyPassword: <password for the private key>
    keystore: <path to your keystore>
    keystorePassword: <password for keystore>
    name: my-java-keystore
    priority: 100
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: realm/v1alpha1/keystorejavakeystore
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    realm: my-realm
