apiVersion: ldap.keycloak.crossplane.io/v1alpha1
kind: MsadLdsUserAccountControlMapper
metadata:
  annotations:
    meta.upbound.io/example-id: ldap/v1alpha1/msadldsuseraccountcontrolmapper
  labels:
    testing.upbound.io/example-name: msad_lds_user_account_control_mapper
  name: msad-lds-user-account-control-mapper
spec:
  forProvider:
    ldapUserFederationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: ldap_user_federation
    name: msad-lds-user-account-control-mapper
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: ldap.keycloak.crossplane.io/v1alpha1
kind: UserFederation
metadata:
  annotations:
    meta.upbound.io/example-id: ldap/v1alpha1/msadldsuseraccountcontrolmapper
  labels:
    testing.upbound.io/example-name: ldap_user_federation
  name: ldap-user-federation
spec:
  forProvider:
    bindCredentialSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    bindDn: cn=admin,dc=example,dc=org
    connectionUrl: ldap://my-ad-server
    name: ad
    rdnLdapAttribute: cn
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    userObjectClasses:
    - person
    - organizationalPerson
    - user
    usernameLdapAttribute: cn
    usersDn: dc=example,dc=org
    uuidLdapAttribute: objectGUID

---

apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: ldap/v1alpha1/msadldsuseraccountcontrolmapper
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm
