apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Memberships
metadata:
  annotations:
    meta.upbound.io/example-id: group/v1alpha1/memberships
  labels:
    testing.upbound.io/example-name: group_members
  name: group-members
spec:
  forProvider:
    groupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: group
    members:
    - ${keycloak_user.user.username}
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: group/v1alpha1/memberships
  labels:
    testing.upbound.io/example-name: group
  name: group
spec:
  forProvider:
    name: my-group
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: group/v1alpha1/memberships
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm

---

apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: group/v1alpha1/memberships
  labels:
    testing.upbound.io/example-name: user
  name: user
spec:
  forProvider:
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    username: my-user
