apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: keycloak-builtin-objects
spec:
  compositeTypeRef:
    apiVersion: keycloak.crossplane.io/v1alpha1
    kind: XBuiltinObjects
  mode: Pipeline
  pipeline:
  - step: pull-provider-configs
    functionRef:
      name: function-extra-resources
    input:
      apiVersion: extra-resources.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        extraResources:
          - kind: Secret
            into: secrets
            apiVersion: v1
            type: Selector 
            selector:
              minMatch: 1
              maxMatch: 100
              matchLabels:
                - key: type
                  type: Value
                  value: provider-credentials
          - kind: Role
            into: roles
            apiVersion: role.keycloak.crossplane.io/v1alpha1
            type: Selector
            selector:
              minMatch: 0
              maxMatch: 20
              matchLabels:
                - key: type
                  type: Value
                  value: modifiedrole
  - step: keycloak-builtin-objects
    functionRef:
      name: function-keycloak-builtin-objects
  - step: automatically-detect-ready-composed-resources
    functionRef:
      name: function-auto-ready