/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type UserAttributeMapperInitParameters struct {

	// When true, the value fetched from LDAP will override the value stored in Keycloak. Defaults to false.
	// When true, the value fetched from LDAP will override the value stored in Keycloak.
	AlwaysReadValueFromLdap *bool `json:"alwaysReadValueFromLdap,omitempty" tf:"always_read_value_from_ldap,omitempty"`

	// Default value to set in LDAP if is_mandatory_in_ldap is true and the value is empty.
	// Default value to set in LDAP if is_mandatory_in_ldap and the value is empty
	AttributeDefaultValue *string `json:"attributeDefaultValue,omitempty" tf:"attribute_default_value,omitempty"`

	// Should be true for binary LDAP attributes.
	// Should be true for binary LDAP attributes
	IsBinaryAttribute *bool `json:"isBinaryAttribute,omitempty" tf:"is_binary_attribute,omitempty"`

	// When true, this attribute must exist in LDAP. Defaults to false.
	// When true, this attribute must exist in LDAP.
	IsMandatoryInLdap *bool `json:"isMandatoryInLdap,omitempty" tf:"is_mandatory_in_ldap,omitempty"`

	// Name of the mapped attribute on the LDAP object.
	// Name of the mapped attribute on LDAP object.
	LdapAttribute *string `json:"ldapAttribute,omitempty" tf:"ldap_attribute,omitempty"`

	// The ID of the LDAP user federation provider to attach this mapper to.
	// The ldap user federation provider to attach this mapper to.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/ldap/v1alpha1.UserFederation
	LdapUserFederationID *string `json:"ldapUserFederationId,omitempty" tf:"ldap_user_federation_id,omitempty"`

	// Reference to a UserFederation in ldap to populate ldapUserFederationId.
	// +kubebuilder:validation:Optional
	LdapUserFederationIDRef *v1.Reference `json:"ldapUserFederationIdRef,omitempty" tf:"-"`

	// Selector for a UserFederation in ldap to populate ldapUserFederationId.
	// +kubebuilder:validation:Optional
	LdapUserFederationIDSelector *v1.Selector `json:"ldapUserFederationIdSelector,omitempty" tf:"-"`

	// Display name of this mapper when displayed in the console.
	// Display name of the mapper when displayed in the console.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// When true, this attribute is not saved back to LDAP when the user attribute is updated in Keycloak. Defaults to false.
	// When true, this attribute is not saved back to LDAP when the user attribute is updated in Keycloak.
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// The realm that this LDAP mapper will exist in.
	// The realm in which the ldap user federation provider exists.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/realm/v1alpha1.Realm
	RealmID *string `json:"realmId,omitempty" tf:"realm_id,omitempty"`

	// Reference to a Realm in realm to populate realmId.
	// +kubebuilder:validation:Optional
	RealmIDRef *v1.Reference `json:"realmIdRef,omitempty" tf:"-"`

	// Selector for a Realm in realm to populate realmId.
	// +kubebuilder:validation:Optional
	RealmIDSelector *v1.Selector `json:"realmIdSelector,omitempty" tf:"-"`

	// Name of the user property or attribute you want to map the LDAP attribute into.
	// Name of the UserModel property or attribute you want to map the LDAP attribute into.
	UserModelAttribute *string `json:"userModelAttribute,omitempty" tf:"user_model_attribute,omitempty"`
}

type UserAttributeMapperObservation struct {

	// When true, the value fetched from LDAP will override the value stored in Keycloak. Defaults to false.
	// When true, the value fetched from LDAP will override the value stored in Keycloak.
	AlwaysReadValueFromLdap *bool `json:"alwaysReadValueFromLdap,omitempty" tf:"always_read_value_from_ldap,omitempty"`

	// Default value to set in LDAP if is_mandatory_in_ldap is true and the value is empty.
	// Default value to set in LDAP if is_mandatory_in_ldap and the value is empty
	AttributeDefaultValue *string `json:"attributeDefaultValue,omitempty" tf:"attribute_default_value,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Should be true for binary LDAP attributes.
	// Should be true for binary LDAP attributes
	IsBinaryAttribute *bool `json:"isBinaryAttribute,omitempty" tf:"is_binary_attribute,omitempty"`

	// When true, this attribute must exist in LDAP. Defaults to false.
	// When true, this attribute must exist in LDAP.
	IsMandatoryInLdap *bool `json:"isMandatoryInLdap,omitempty" tf:"is_mandatory_in_ldap,omitempty"`

	// Name of the mapped attribute on the LDAP object.
	// Name of the mapped attribute on LDAP object.
	LdapAttribute *string `json:"ldapAttribute,omitempty" tf:"ldap_attribute,omitempty"`

	// The ID of the LDAP user federation provider to attach this mapper to.
	// The ldap user federation provider to attach this mapper to.
	LdapUserFederationID *string `json:"ldapUserFederationId,omitempty" tf:"ldap_user_federation_id,omitempty"`

	// Display name of this mapper when displayed in the console.
	// Display name of the mapper when displayed in the console.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// When true, this attribute is not saved back to LDAP when the user attribute is updated in Keycloak. Defaults to false.
	// When true, this attribute is not saved back to LDAP when the user attribute is updated in Keycloak.
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// The realm that this LDAP mapper will exist in.
	// The realm in which the ldap user federation provider exists.
	RealmID *string `json:"realmId,omitempty" tf:"realm_id,omitempty"`

	// Name of the user property or attribute you want to map the LDAP attribute into.
	// Name of the UserModel property or attribute you want to map the LDAP attribute into.
	UserModelAttribute *string `json:"userModelAttribute,omitempty" tf:"user_model_attribute,omitempty"`
}

type UserAttributeMapperParameters struct {

	// When true, the value fetched from LDAP will override the value stored in Keycloak. Defaults to false.
	// When true, the value fetched from LDAP will override the value stored in Keycloak.
	// +kubebuilder:validation:Optional
	AlwaysReadValueFromLdap *bool `json:"alwaysReadValueFromLdap,omitempty" tf:"always_read_value_from_ldap,omitempty"`

	// Default value to set in LDAP if is_mandatory_in_ldap is true and the value is empty.
	// Default value to set in LDAP if is_mandatory_in_ldap and the value is empty
	// +kubebuilder:validation:Optional
	AttributeDefaultValue *string `json:"attributeDefaultValue,omitempty" tf:"attribute_default_value,omitempty"`

	// Should be true for binary LDAP attributes.
	// Should be true for binary LDAP attributes
	// +kubebuilder:validation:Optional
	IsBinaryAttribute *bool `json:"isBinaryAttribute,omitempty" tf:"is_binary_attribute,omitempty"`

	// When true, this attribute must exist in LDAP. Defaults to false.
	// When true, this attribute must exist in LDAP.
	// +kubebuilder:validation:Optional
	IsMandatoryInLdap *bool `json:"isMandatoryInLdap,omitempty" tf:"is_mandatory_in_ldap,omitempty"`

	// Name of the mapped attribute on the LDAP object.
	// Name of the mapped attribute on LDAP object.
	// +kubebuilder:validation:Optional
	LdapAttribute *string `json:"ldapAttribute,omitempty" tf:"ldap_attribute,omitempty"`

	// The ID of the LDAP user federation provider to attach this mapper to.
	// The ldap user federation provider to attach this mapper to.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/ldap/v1alpha1.UserFederation
	// +kubebuilder:validation:Optional
	LdapUserFederationID *string `json:"ldapUserFederationId,omitempty" tf:"ldap_user_federation_id,omitempty"`

	// Reference to a UserFederation in ldap to populate ldapUserFederationId.
	// +kubebuilder:validation:Optional
	LdapUserFederationIDRef *v1.Reference `json:"ldapUserFederationIdRef,omitempty" tf:"-"`

	// Selector for a UserFederation in ldap to populate ldapUserFederationId.
	// +kubebuilder:validation:Optional
	LdapUserFederationIDSelector *v1.Selector `json:"ldapUserFederationIdSelector,omitempty" tf:"-"`

	// Display name of this mapper when displayed in the console.
	// Display name of the mapper when displayed in the console.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// When true, this attribute is not saved back to LDAP when the user attribute is updated in Keycloak. Defaults to false.
	// When true, this attribute is not saved back to LDAP when the user attribute is updated in Keycloak.
	// +kubebuilder:validation:Optional
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// The realm that this LDAP mapper will exist in.
	// The realm in which the ldap user federation provider exists.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/realm/v1alpha1.Realm
	// +kubebuilder:validation:Optional
	RealmID *string `json:"realmId,omitempty" tf:"realm_id,omitempty"`

	// Reference to a Realm in realm to populate realmId.
	// +kubebuilder:validation:Optional
	RealmIDRef *v1.Reference `json:"realmIdRef,omitempty" tf:"-"`

	// Selector for a Realm in realm to populate realmId.
	// +kubebuilder:validation:Optional
	RealmIDSelector *v1.Selector `json:"realmIdSelector,omitempty" tf:"-"`

	// Name of the user property or attribute you want to map the LDAP attribute into.
	// Name of the UserModel property or attribute you want to map the LDAP attribute into.
	// +kubebuilder:validation:Optional
	UserModelAttribute *string `json:"userModelAttribute,omitempty" tf:"user_model_attribute,omitempty"`
}

// UserAttributeMapperSpec defines the desired state of UserAttributeMapper
type UserAttributeMapperSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     UserAttributeMapperParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserAttributeMapperInitParameters `json:"initProvider,omitempty"`
}

// UserAttributeMapperStatus defines the observed state of UserAttributeMapper.
type UserAttributeMapperStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserAttributeMapperObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// UserAttributeMapper is the Schema for the UserAttributeMappers API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,keycloak}
type UserAttributeMapper struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ldapAttribute) || (has(self.initProvider) && has(self.initProvider.ldapAttribute))",message="spec.forProvider.ldapAttribute is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.userModelAttribute) || (has(self.initProvider) && has(self.initProvider.userModelAttribute))",message="spec.forProvider.userModelAttribute is a required parameter"
	Spec   UserAttributeMapperSpec   `json:"spec"`
	Status UserAttributeMapperStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserAttributeMapperList contains a list of UserAttributeMappers
type UserAttributeMapperList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UserAttributeMapper `json:"items"`
}

// Repository type metadata.
var (
	UserAttributeMapper_Kind             = "UserAttributeMapper"
	UserAttributeMapper_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UserAttributeMapper_Kind}.String()
	UserAttributeMapper_KindAPIVersion   = UserAttributeMapper_Kind + "." + CRDGroupVersion.String()
	UserAttributeMapper_GroupVersionKind = CRDGroupVersion.WithKind(UserAttributeMapper_Kind)
)

func init() {
	SchemeBuilder.Register(&UserAttributeMapper{}, &UserAttributeMapperList{})
}
