apiVersion: identityprovider.keycloak.m.crossplane.io/v1alpha1
kind: IdentityProviderMapper
metadata:
  annotations:
    meta.upbound.io/example-id: identityprovider/v1alpha1/identityprovidermapper
  labels:
    testing.upbound.io/example-name: oidc
  name: oidc
  namespace: upbound-system
spec:
  forProvider:
    extraConfig:
      Claim: my-email-claim
      UserAttribute: email
      syncMode: INHERIT
    identityProviderAlias: my-idp
    identityProviderMapper: '%s-user-attribute-idp-mapper'
    name: email-attribute-importer
    realmSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: oidc.keycloak.m.crossplane.io/v1alpha1
kind: IdentityProvider
metadata:
  annotations:
    meta.upbound.io/example-id: identityprovider/v1alpha1/identityprovidermapper
  labels:
    testing.upbound.io/example-name: oidc
  name: oidc
  namespace: upbound-system
spec:
  forProvider:
    alias: oidc
    authorizationUrl: https://example.com/auth
    clientIdSecretRef:
      key: example-key
      name: example-secret
    clientSecretSecretRef:
      key: example-key
      name: example-secret
    defaultScopes: openid random profile
    realmSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    tokenUrl: https://example.com/token

---

apiVersion: realm.keycloak.m.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: identityprovider/v1alpha1/identityprovidermapper
  labels:
    testing.upbound.io/example-name: realm
  name: realm
  namespace: upbound-system
spec:
  forProvider:
    enabled: true
    realm: my-realm
