/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ClientAuthorizationPolicyInitParameters struct {

	// The decision strategy, can be one of UNANIMOUS, AFFIRMATIVE, or CONSENSUS.
	DecisionStrategy *string `json:"decisionStrategy,omitempty" tf:"decision_strategy,omitempty"`

	// A description for the authorization policy.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The logic, can be one of POSITIVE or NEGATIVE. Defaults to POSITIVE.
	Logic *string `json:"logic,omitempty" tf:"logic,omitempty"`

	// The name of the policy.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The realm this policy exists in.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/namespaced/realm/v1alpha1.Realm
	RealmID *string `json:"realmId,omitempty" tf:"realm_id,omitempty"`

	// Reference to a Realm in realm to populate realmId.
	// +kubebuilder:validation:Optional
	RealmIDRef *v1.NamespacedReference `json:"realmIdRef,omitempty" tf:"-"`

	// Selector for a Realm in realm to populate realmId.
	// +kubebuilder:validation:Optional
	RealmIDSelector *v1.NamespacedSelector `json:"realmIdSelector,omitempty" tf:"-"`

	// The ID of the resource server this policy is attached to.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/namespaced/openidclient/v1alpha2.Client
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-keycloak/config/common.UUIDExtractor()
	ResourceServerID *string `json:"resourceServerId,omitempty" tf:"resource_server_id,omitempty"`

	// Reference to a Client in openidclient to populate resourceServerId.
	// +kubebuilder:validation:Optional
	ResourceServerIDRef *v1.NamespacedReference `json:"resourceServerIdRef,omitempty" tf:"-"`

	// Selector for a Client in openidclient to populate resourceServerId.
	// +kubebuilder:validation:Optional
	ResourceServerIDSelector *v1.NamespacedSelector `json:"resourceServerIdSelector,omitempty" tf:"-"`

	// is whatever your PolicyProviderFactory.getId() returns.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ClientAuthorizationPolicyObservation struct {

	// The decision strategy, can be one of UNANIMOUS, AFFIRMATIVE, or CONSENSUS.
	DecisionStrategy *string `json:"decisionStrategy,omitempty" tf:"decision_strategy,omitempty"`

	// A description for the authorization policy.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Policy ID representing the policy.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The logic, can be one of POSITIVE or NEGATIVE. Defaults to POSITIVE.
	Logic *string `json:"logic,omitempty" tf:"logic,omitempty"`

	// The name of the policy.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The realm this policy exists in.
	RealmID *string `json:"realmId,omitempty" tf:"realm_id,omitempty"`

	// The ID of the resource server this policy is attached to.
	ResourceServerID *string `json:"resourceServerId,omitempty" tf:"resource_server_id,omitempty"`

	// is whatever your PolicyProviderFactory.getId() returns.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ClientAuthorizationPolicyParameters struct {

	// The decision strategy, can be one of UNANIMOUS, AFFIRMATIVE, or CONSENSUS.
	// +kubebuilder:validation:Optional
	DecisionStrategy *string `json:"decisionStrategy,omitempty" tf:"decision_strategy,omitempty"`

	// A description for the authorization policy.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The logic, can be one of POSITIVE or NEGATIVE. Defaults to POSITIVE.
	// +kubebuilder:validation:Optional
	Logic *string `json:"logic,omitempty" tf:"logic,omitempty"`

	// The name of the policy.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The realm this policy exists in.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/namespaced/realm/v1alpha1.Realm
	// +kubebuilder:validation:Optional
	RealmID *string `json:"realmId,omitempty" tf:"realm_id,omitempty"`

	// Reference to a Realm in realm to populate realmId.
	// +kubebuilder:validation:Optional
	RealmIDRef *v1.NamespacedReference `json:"realmIdRef,omitempty" tf:"-"`

	// Selector for a Realm in realm to populate realmId.
	// +kubebuilder:validation:Optional
	RealmIDSelector *v1.NamespacedSelector `json:"realmIdSelector,omitempty" tf:"-"`

	// The ID of the resource server this policy is attached to.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/namespaced/openidclient/v1alpha2.Client
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-keycloak/config/common.UUIDExtractor()
	// +kubebuilder:validation:Optional
	ResourceServerID *string `json:"resourceServerId,omitempty" tf:"resource_server_id,omitempty"`

	// Reference to a Client in openidclient to populate resourceServerId.
	// +kubebuilder:validation:Optional
	ResourceServerIDRef *v1.NamespacedReference `json:"resourceServerIdRef,omitempty" tf:"-"`

	// Selector for a Client in openidclient to populate resourceServerId.
	// +kubebuilder:validation:Optional
	ResourceServerIDSelector *v1.NamespacedSelector `json:"resourceServerIdSelector,omitempty" tf:"-"`

	// is whatever your PolicyProviderFactory.getId() returns.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// ClientAuthorizationPolicySpec defines the desired state of ClientAuthorizationPolicy
type ClientAuthorizationPolicySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ClientAuthorizationPolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClientAuthorizationPolicyInitParameters `json:"initProvider,omitempty"`
}

// ClientAuthorizationPolicyStatus defines the observed state of ClientAuthorizationPolicy.
type ClientAuthorizationPolicyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ClientAuthorizationPolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ClientAuthorizationPolicy is the Schema for the ClientAuthorizationPolicys API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,keycloak}
type ClientAuthorizationPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.decisionStrategy) || (has(self.initProvider) && has(self.initProvider.decisionStrategy))",message="spec.forProvider.decisionStrategy is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   ClientAuthorizationPolicySpec   `json:"spec"`
	Status ClientAuthorizationPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClientAuthorizationPolicyList contains a list of ClientAuthorizationPolicys
type ClientAuthorizationPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClientAuthorizationPolicy `json:"items"`
}

// Repository type metadata.
var (
	ClientAuthorizationPolicy_Kind             = "ClientAuthorizationPolicy"
	ClientAuthorizationPolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ClientAuthorizationPolicy_Kind}.String()
	ClientAuthorizationPolicy_KindAPIVersion   = ClientAuthorizationPolicy_Kind + "." + CRDGroupVersion.String()
	ClientAuthorizationPolicy_GroupVersionKind = CRDGroupVersion.WithKind(ClientAuthorizationPolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&ClientAuthorizationPolicy{}, &ClientAuthorizationPolicyList{})
}
