apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/client
  labels:
    testing.upbound.io/example-name: openid_client
  name: openid-client
  namespace: upbound-system
spec:
  forProvider:
    accessType: CONFIDENTIAL
    clientId: test-client
    enabled: true
    extraConfig:
      key1: value1
      key2: value2
    loginTheme: keycloak
    name: test client
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    standardFlowEnabled: true
    validRedirectUris:
    - http://localhost:8080/openid-callback

---

apiVersion: realm.keycloak.m.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/client
  labels:
    testing.upbound.io/example-name: realm
  name: realm
  namespace: upbound-system
spec:
  forProvider:
    enabled: true
    realm: my-realm
