apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientServiceAccountRole
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientserviceaccountrole
  labels:
    testing.upbound.io/example-name: client2_service_account_role
  name: client2-service-account-role
  namespace: upbound-system
spec:
  forProvider:
    clientIdSelector:
      matchLabels:
        testing.upbound.io/example-name: client1
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: client1_role
    serviceAccountUserClientIdSelector:
      matchLabels:
        testing.upbound.io/example-name: client2

---

apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientserviceaccountrole
  labels:
    testing.upbound.io/example-name: client1
  name: client1
  namespace: upbound-system
spec:
  forProvider:
    name: client1
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientserviceaccountrole
  labels:
    testing.upbound.io/example-name: client2
  name: client2
  namespace: upbound-system
spec:
  forProvider:
    name: client2
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    serviceAccountsEnabled: true

---

apiVersion: realm.keycloak.m.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientserviceaccountrole
  labels:
    testing.upbound.io/example-name: realm
  name: realm
  namespace: upbound-system
spec:
  forProvider:
    enabled: true
    realm: my-realm

---

apiVersion: role.keycloak.m.crossplane.io/v1alpha1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientserviceaccountrole
  labels:
    testing.upbound.io/example-name: client1_role
  name: client1-role
  namespace: upbound-system
spec:
  forProvider:
    clientIdSelector:
      matchLabels:
        testing.upbound.io/example-name: client1
    description: A role that client1 provides
    name: my-client1-role
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
