apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientGroupPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientgrouppolicy
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: upbound-system
spec:
  forProvider:
    decisionStrategy: UNANIMOUS
    groups:
    - extendChildren: false
      idSelector:
        matchLabels:
          testing.upbound.io/example-name: group1
      path: ${keycloak_group.group1.path}
    - extendChildren: true
      idSelector:
        matchLabels:
          testing.upbound.io/example-name: group2
      path: ${keycloak_group.group2.path}
    logic: POSITIVE
    name: group_policy
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    resourceServerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientgrouppolicy
  labels:
    testing.upbound.io/example-name: group1
  name: group1
  namespace: upbound-system
spec:
  forProvider:
    name: group1
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientgrouppolicy
  labels:
    testing.upbound.io/example-name: group2
  name: group2
  namespace: upbound-system
spec:
  forProvider:
    name: group2
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientgrouppolicy
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: upbound-system
spec:
  forProvider:
    accessType: CONFIDENTIAL
    authorization:
    - policyEnforcementMode: ENFORCING
    clientId: client_id
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    serviceAccountsEnabled: true

---

apiVersion: realm.keycloak.m.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientgrouppolicy
  labels:
    testing.upbound.io/example-name: realm
  name: realm
  namespace: upbound-system
spec:
  forProvider:
    enabled: true
    realm: my-realm
