apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientServiceAccountRealmRole
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientserviceaccountrealmrole
  labels:
    testing.upbound.io/example-name: client_service_account_role
  name: client-service-account-role
  namespace: upbound-system
spec:
  forProvider:
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    role: my-realm-role
    serviceAccountUserClientIdSelector:
      matchLabels:
        testing.upbound.io/example-name: client

---

apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientserviceaccountrealmrole
  labels:
    testing.upbound.io/example-name: client
  name: client
  namespace: upbound-system
spec:
  forProvider:
    name: client
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    serviceAccountsEnabled: true

---

apiVersion: realm.keycloak.m.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientserviceaccountrealmrole
  labels:
    testing.upbound.io/example-name: realm
  name: realm
  namespace: upbound-system
spec:
  forProvider:
    enabled: true
    realm: my-realm

---

apiVersion: role.keycloak.m.crossplane.io/v1alpha1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientserviceaccountrealmrole
  labels:
    testing.upbound.io/example-name: realm_role
  name: realm-role
  namespace: upbound-system
spec:
  forProvider:
    name: my-realm-role
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
