apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  name: argocd-admin
spec:
  forProvider:
    realmId: "platform"
    name: "argocd-admin"
    description: "ArgoCD administrator role"
  providerConfigRef:
    name: keycloak-provider-config
---
apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  name: argocd-readonly
spec:
  forProvider:
    realmId: "platform"
    name: "argocd-readonly"
    description: "ArgoCD read-only role"
  providerConfigRef:
    name: keycloak-provider-config
