apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: platform-admins
spec:
  forProvider:
    name: "platform-admins"
    realmId: "platform"
  providerConfigRef:
    name: keycloak-provider-config
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: platform-viewers
spec:
  forProvider:
    name: "platform-viewers"
    realmId: "platform"
  providerConfigRef:
    name: keycloak-provider-config
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: platform-admin-roles
spec:
  forProvider:
    realmId: "platform"
    groupIdRef:
      name: platform-admins
    roleIdsRefs:
      - name: argocd-admin
  providerConfigRef:
    name: keycloak-provider-config
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: platform-viewer-roles
spec:
  forProvider:
    realmId: "platform"
    groupIdRef:
      name: platform-viewers
    roleIdsRefs:
      - name: argocd-readonly
  providerConfigRef:
    name: keycloak-provider-config
