apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  scopes: "[groups]"
  policy.csv: |
    g, argocd-admin, role:admin
    g, argocd-readonly, role:readonly
