apiVersion: ldap.keycloak.m.crossplane.io/v1alpha1
kind: HardcodedGroupMapper
metadata:
  annotations:
    meta.upbound.io/example-id: ldap/v1alpha1/hardcodedgroupmapper
  labels:
    testing.upbound.io/example-name: assign_group_to_users
  name: assign-group-to-users
  namespace: upbound-system
spec:
  forProvider:
    groupSelector:
      matchLabels:
        testing.upbound.io/example-name: realm_group
    ldapUserFederationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: ldap_user_federation
    name: assign-group-to-users
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: ldap/v1alpha1/hardcodedgroupmapper
  labels:
    testing.upbound.io/example-name: realm_group
  name: realm-group
  namespace: upbound-system
spec:
  forProvider:
    name: my-group
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: ldap.keycloak.m.crossplane.io/v1alpha1
kind: UserFederation
metadata:
  annotations:
    meta.upbound.io/example-id: ldap/v1alpha1/hardcodedgroupmapper
  labels:
    testing.upbound.io/example-name: ldap_user_federation
  name: ldap-user-federation
  namespace: upbound-system
spec:
  forProvider:
    bindCredentialSecretRef:
      key: example-key
      name: example-secret
    bindDn: cn=admin,dc=example,dc=org
    connectionUrl: ldap://openldap
    name: openldap
    rdnLdapAttribute: cn
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    userObjectClasses:
    - simpleSecurityObject
    - organizationalRole
    usernameLdapAttribute: cn
    usersDn: dc=example,dc=org
    uuidLdapAttribute: entryDN

---

apiVersion: realm.keycloak.m.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: ldap/v1alpha1/hardcodedgroupmapper
  labels:
    testing.upbound.io/example-name: realm
  name: realm
  namespace: upbound-system
spec:
  forProvider:
    enabled: true
    realm: my-realm
