apiVersion: oidc.keycloak.m.crossplane.io/v1alpha1
kind: MicrosoftIdentityProvider
metadata:
  annotations:
    meta.upbound.io/example-id: oidc/v1alpha1/microsoftidentityprovider
  labels:
    testing.upbound.io/example-name: microsoft
  name: microsoft
  namespace: upbound-system
spec:
  forProvider:
    clientIdSecretRef:
      key: example-key
      name: example-secret
    clientSecretSecretRef:
      key: example-key
      name: example-secret
    displayName: myMicrosoft-idp
    extraConfig:
      myCustomConfigKey: value
    realmSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    syncMode: IMPORT

---

apiVersion: realm.keycloak.m.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: oidc/v1alpha1/microsoftidentityprovider
  labels:
    testing.upbound.io/example-name: realm
  name: realm
  namespace: upbound-system
spec:
  forProvider:
    enabled: true
    realm: my-realm
