/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ClientAggregatePolicyInitParameters struct {

	// A list of policy IDs to aggregate.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/cluster/openidclient/v1alpha1.ClientClientPolicy
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-keycloak/config/common.UUIDExtractor()
	// +listType=set
	ClientPolicies []*string `json:"clientPolicies,omitempty" tf:"client_policies,omitempty"`

	// References to ClientClientPolicy in openidclient to populate clientPolicies.
	// +kubebuilder:validation:Optional
	ClientPoliciesRefs []v1.Reference `json:"clientPoliciesRefs,omitempty" tf:"-"`

	// Selector for a list of ClientClientPolicy in openidclient to populate clientPolicies.
	// +kubebuilder:validation:Optional
	ClientPoliciesSelector *v1.Selector `json:"clientPoliciesSelector,omitempty" tf:"-"`

	// The decision strategy, can be one of UNANIMOUS, AFFIRMATIVE, or CONSENSUS.
	DecisionStrategy *string `json:"decisionStrategy,omitempty" tf:"decision_strategy,omitempty"`

	// A description for the authorization policy.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A list of policy IDs to aggregate.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/cluster/openidclient/v1alpha1.ClientGroupPolicy
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-keycloak/config/common.UUIDExtractor()
	// +listType=set
	GroupPolicies []*string `json:"groupPolicies,omitempty" tf:"group_policies,omitempty"`

	// References to ClientGroupPolicy in openidclient to populate groupPolicies.
	// +kubebuilder:validation:Optional
	GroupPoliciesRefs []v1.Reference `json:"groupPoliciesRefs,omitempty" tf:"-"`

	// Selector for a list of ClientGroupPolicy in openidclient to populate groupPolicies.
	// +kubebuilder:validation:Optional
	GroupPoliciesSelector *v1.Selector `json:"groupPoliciesSelector,omitempty" tf:"-"`

	// The logic, can be one of POSITIVE or NEGATIVE. Defaults to POSITIVE.
	Logic *string `json:"logic,omitempty" tf:"logic,omitempty"`

	// The name of the policy.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A list of policy IDs to aggregate.
	// +listType=set
	Policies []*string `json:"policies,omitempty" tf:"policies,omitempty"`

	// The realm this policy exists in.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/cluster/realm/v1alpha1.Realm
	RealmID *string `json:"realmId,omitempty" tf:"realm_id,omitempty"`

	// Reference to a Realm in realm to populate realmId.
	// +kubebuilder:validation:Optional
	RealmIDRef *v1.Reference `json:"realmIdRef,omitempty" tf:"-"`

	// Selector for a Realm in realm to populate realmId.
	// +kubebuilder:validation:Optional
	RealmIDSelector *v1.Selector `json:"realmIdSelector,omitempty" tf:"-"`

	// A list of policy IDs to aggregate.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/cluster/openidclient/v1alpha1.ClientRegexPolicy
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-keycloak/config/common.UUIDExtractor()
	// +listType=set
	RegexPolicies []*string `json:"regexPolicies,omitempty" tf:"regex_policies,omitempty"`

	// References to ClientRegexPolicy in openidclient to populate regexPolicies.
	// +kubebuilder:validation:Optional
	RegexPoliciesRefs []v1.Reference `json:"regexPoliciesRefs,omitempty" tf:"-"`

	// Selector for a list of ClientRegexPolicy in openidclient to populate regexPolicies.
	// +kubebuilder:validation:Optional
	RegexPoliciesSelector *v1.Selector `json:"regexPoliciesSelector,omitempty" tf:"-"`

	// The ID of the resource server.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/cluster/openidclient/v1alpha2.Client
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-keycloak/config/common.UUIDExtractor()
	ResourceServerID *string `json:"resourceServerId,omitempty" tf:"resource_server_id,omitempty"`

	// Reference to a Client in openidclient to populate resourceServerId.
	// +kubebuilder:validation:Optional
	ResourceServerIDRef *v1.Reference `json:"resourceServerIdRef,omitempty" tf:"-"`

	// Selector for a Client in openidclient to populate resourceServerId.
	// +kubebuilder:validation:Optional
	ResourceServerIDSelector *v1.Selector `json:"resourceServerIdSelector,omitempty" tf:"-"`

	// A list of policy IDs to aggregate.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/cluster/openidclient/v1alpha1.ClientRolePolicy
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-keycloak/config/common.UUIDExtractor()
	// +listType=set
	RolePolicies []*string `json:"rolePolicies,omitempty" tf:"role_policies,omitempty"`

	// References to ClientRolePolicy in openidclient to populate rolePolicies.
	// +kubebuilder:validation:Optional
	RolePoliciesRefs []v1.Reference `json:"rolePoliciesRefs,omitempty" tf:"-"`

	// Selector for a list of ClientRolePolicy in openidclient to populate rolePolicies.
	// +kubebuilder:validation:Optional
	RolePoliciesSelector *v1.Selector `json:"rolePoliciesSelector,omitempty" tf:"-"`

	// A list of policy IDs to aggregate.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/cluster/openidclient/v1alpha1.ClientTimePolicy
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-keycloak/config/common.UUIDExtractor()
	// +listType=set
	TimePolicies []*string `json:"timePolicies,omitempty" tf:"time_policies,omitempty"`

	// References to ClientTimePolicy in openidclient to populate timePolicies.
	// +kubebuilder:validation:Optional
	TimePoliciesRefs []v1.Reference `json:"timePoliciesRefs,omitempty" tf:"-"`

	// Selector for a list of ClientTimePolicy in openidclient to populate timePolicies.
	// +kubebuilder:validation:Optional
	TimePoliciesSelector *v1.Selector `json:"timePoliciesSelector,omitempty" tf:"-"`

	// A list of policy IDs to aggregate.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/cluster/openidclient/v1alpha1.ClientUserPolicy
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-keycloak/config/common.UUIDExtractor()
	// +listType=set
	UserPolicies []*string `json:"userPolicies,omitempty" tf:"user_policies,omitempty"`

	// References to ClientUserPolicy in openidclient to populate userPolicies.
	// +kubebuilder:validation:Optional
	UserPoliciesRefs []v1.Reference `json:"userPoliciesRefs,omitempty" tf:"-"`

	// Selector for a list of ClientUserPolicy in openidclient to populate userPolicies.
	// +kubebuilder:validation:Optional
	UserPoliciesSelector *v1.Selector `json:"userPoliciesSelector,omitempty" tf:"-"`
}

type ClientAggregatePolicyObservation struct {

	// A list of policy IDs to aggregate.
	// +listType=set
	ClientPolicies []*string `json:"clientPolicies,omitempty" tf:"client_policies,omitempty"`

	// The decision strategy, can be one of UNANIMOUS, AFFIRMATIVE, or CONSENSUS.
	DecisionStrategy *string `json:"decisionStrategy,omitempty" tf:"decision_strategy,omitempty"`

	// A description for the authorization policy.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A list of policy IDs to aggregate.
	// +listType=set
	GroupPolicies []*string `json:"groupPolicies,omitempty" tf:"group_policies,omitempty"`

	// Policy ID representing the aggregate policy.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The logic, can be one of POSITIVE or NEGATIVE. Defaults to POSITIVE.
	Logic *string `json:"logic,omitempty" tf:"logic,omitempty"`

	// The name of the policy.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A list of policy IDs to aggregate.
	// +listType=set
	Policies []*string `json:"policies,omitempty" tf:"policies,omitempty"`

	// The realm this policy exists in.
	RealmID *string `json:"realmId,omitempty" tf:"realm_id,omitempty"`

	// A list of policy IDs to aggregate.
	// +listType=set
	RegexPolicies []*string `json:"regexPolicies,omitempty" tf:"regex_policies,omitempty"`

	// The ID of the resource server.
	ResourceServerID *string `json:"resourceServerId,omitempty" tf:"resource_server_id,omitempty"`

	// A list of policy IDs to aggregate.
	// +listType=set
	RolePolicies []*string `json:"rolePolicies,omitempty" tf:"role_policies,omitempty"`

	// A list of policy IDs to aggregate.
	// +listType=set
	TimePolicies []*string `json:"timePolicies,omitempty" tf:"time_policies,omitempty"`

	// A list of policy IDs to aggregate.
	// +listType=set
	UserPolicies []*string `json:"userPolicies,omitempty" tf:"user_policies,omitempty"`
}

type ClientAggregatePolicyParameters struct {

	// A list of policy IDs to aggregate.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/cluster/openidclient/v1alpha1.ClientClientPolicy
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-keycloak/config/common.UUIDExtractor()
	// +kubebuilder:validation:Optional
	// +listType=set
	ClientPolicies []*string `json:"clientPolicies,omitempty" tf:"client_policies,omitempty"`

	// References to ClientClientPolicy in openidclient to populate clientPolicies.
	// +kubebuilder:validation:Optional
	ClientPoliciesRefs []v1.Reference `json:"clientPoliciesRefs,omitempty" tf:"-"`

	// Selector for a list of ClientClientPolicy in openidclient to populate clientPolicies.
	// +kubebuilder:validation:Optional
	ClientPoliciesSelector *v1.Selector `json:"clientPoliciesSelector,omitempty" tf:"-"`

	// The decision strategy, can be one of UNANIMOUS, AFFIRMATIVE, or CONSENSUS.
	// +kubebuilder:validation:Optional
	DecisionStrategy *string `json:"decisionStrategy,omitempty" tf:"decision_strategy,omitempty"`

	// A description for the authorization policy.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A list of policy IDs to aggregate.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/cluster/openidclient/v1alpha1.ClientGroupPolicy
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-keycloak/config/common.UUIDExtractor()
	// +kubebuilder:validation:Optional
	// +listType=set
	GroupPolicies []*string `json:"groupPolicies,omitempty" tf:"group_policies,omitempty"`

	// References to ClientGroupPolicy in openidclient to populate groupPolicies.
	// +kubebuilder:validation:Optional
	GroupPoliciesRefs []v1.Reference `json:"groupPoliciesRefs,omitempty" tf:"-"`

	// Selector for a list of ClientGroupPolicy in openidclient to populate groupPolicies.
	// +kubebuilder:validation:Optional
	GroupPoliciesSelector *v1.Selector `json:"groupPoliciesSelector,omitempty" tf:"-"`

	// The logic, can be one of POSITIVE or NEGATIVE. Defaults to POSITIVE.
	// +kubebuilder:validation:Optional
	Logic *string `json:"logic,omitempty" tf:"logic,omitempty"`

	// The name of the policy.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A list of policy IDs to aggregate.
	// +kubebuilder:validation:Optional
	// +listType=set
	Policies []*string `json:"policies,omitempty" tf:"policies,omitempty"`

	// The realm this policy exists in.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/cluster/realm/v1alpha1.Realm
	// +kubebuilder:validation:Optional
	RealmID *string `json:"realmId,omitempty" tf:"realm_id,omitempty"`

	// Reference to a Realm in realm to populate realmId.
	// +kubebuilder:validation:Optional
	RealmIDRef *v1.Reference `json:"realmIdRef,omitempty" tf:"-"`

	// Selector for a Realm in realm to populate realmId.
	// +kubebuilder:validation:Optional
	RealmIDSelector *v1.Selector `json:"realmIdSelector,omitempty" tf:"-"`

	// A list of policy IDs to aggregate.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/cluster/openidclient/v1alpha1.ClientRegexPolicy
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-keycloak/config/common.UUIDExtractor()
	// +kubebuilder:validation:Optional
	// +listType=set
	RegexPolicies []*string `json:"regexPolicies,omitempty" tf:"regex_policies,omitempty"`

	// References to ClientRegexPolicy in openidclient to populate regexPolicies.
	// +kubebuilder:validation:Optional
	RegexPoliciesRefs []v1.Reference `json:"regexPoliciesRefs,omitempty" tf:"-"`

	// Selector for a list of ClientRegexPolicy in openidclient to populate regexPolicies.
	// +kubebuilder:validation:Optional
	RegexPoliciesSelector *v1.Selector `json:"regexPoliciesSelector,omitempty" tf:"-"`

	// The ID of the resource server.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/cluster/openidclient/v1alpha2.Client
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-keycloak/config/common.UUIDExtractor()
	// +kubebuilder:validation:Optional
	ResourceServerID *string `json:"resourceServerId,omitempty" tf:"resource_server_id,omitempty"`

	// Reference to a Client in openidclient to populate resourceServerId.
	// +kubebuilder:validation:Optional
	ResourceServerIDRef *v1.Reference `json:"resourceServerIdRef,omitempty" tf:"-"`

	// Selector for a Client in openidclient to populate resourceServerId.
	// +kubebuilder:validation:Optional
	ResourceServerIDSelector *v1.Selector `json:"resourceServerIdSelector,omitempty" tf:"-"`

	// A list of policy IDs to aggregate.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/cluster/openidclient/v1alpha1.ClientRolePolicy
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-keycloak/config/common.UUIDExtractor()
	// +kubebuilder:validation:Optional
	// +listType=set
	RolePolicies []*string `json:"rolePolicies,omitempty" tf:"role_policies,omitempty"`

	// References to ClientRolePolicy in openidclient to populate rolePolicies.
	// +kubebuilder:validation:Optional
	RolePoliciesRefs []v1.Reference `json:"rolePoliciesRefs,omitempty" tf:"-"`

	// Selector for a list of ClientRolePolicy in openidclient to populate rolePolicies.
	// +kubebuilder:validation:Optional
	RolePoliciesSelector *v1.Selector `json:"rolePoliciesSelector,omitempty" tf:"-"`

	// A list of policy IDs to aggregate.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/cluster/openidclient/v1alpha1.ClientTimePolicy
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-keycloak/config/common.UUIDExtractor()
	// +kubebuilder:validation:Optional
	// +listType=set
	TimePolicies []*string `json:"timePolicies,omitempty" tf:"time_policies,omitempty"`

	// References to ClientTimePolicy in openidclient to populate timePolicies.
	// +kubebuilder:validation:Optional
	TimePoliciesRefs []v1.Reference `json:"timePoliciesRefs,omitempty" tf:"-"`

	// Selector for a list of ClientTimePolicy in openidclient to populate timePolicies.
	// +kubebuilder:validation:Optional
	TimePoliciesSelector *v1.Selector `json:"timePoliciesSelector,omitempty" tf:"-"`

	// A list of policy IDs to aggregate.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/cluster/openidclient/v1alpha1.ClientUserPolicy
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-keycloak/config/common.UUIDExtractor()
	// +kubebuilder:validation:Optional
	// +listType=set
	UserPolicies []*string `json:"userPolicies,omitempty" tf:"user_policies,omitempty"`

	// References to ClientUserPolicy in openidclient to populate userPolicies.
	// +kubebuilder:validation:Optional
	UserPoliciesRefs []v1.Reference `json:"userPoliciesRefs,omitempty" tf:"-"`

	// Selector for a list of ClientUserPolicy in openidclient to populate userPolicies.
	// +kubebuilder:validation:Optional
	UserPoliciesSelector *v1.Selector `json:"userPoliciesSelector,omitempty" tf:"-"`
}

// ClientAggregatePolicySpec defines the desired state of ClientAggregatePolicy
type ClientAggregatePolicySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ClientAggregatePolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClientAggregatePolicyInitParameters `json:"initProvider,omitempty"`
}

// ClientAggregatePolicyStatus defines the observed state of ClientAggregatePolicy.
type ClientAggregatePolicyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ClientAggregatePolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ClientAggregatePolicy is the Schema for the ClientAggregatePolicys API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,keycloak}
type ClientAggregatePolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.decisionStrategy) || (has(self.initProvider) && has(self.initProvider.decisionStrategy))",message="spec.forProvider.decisionStrategy is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.policies) || (has(self.initProvider) && has(self.initProvider.policies))",message="spec.forProvider.policies is a required parameter"
	Spec   ClientAggregatePolicySpec   `json:"spec"`
	Status ClientAggregatePolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClientAggregatePolicyList contains a list of ClientAggregatePolicys
type ClientAggregatePolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClientAggregatePolicy `json:"items"`
}

// Repository type metadata.
var (
	ClientAggregatePolicy_Kind             = "ClientAggregatePolicy"
	ClientAggregatePolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ClientAggregatePolicy_Kind}.String()
	ClientAggregatePolicy_KindAPIVersion   = ClientAggregatePolicy_Kind + "." + CRDGroupVersion.String()
	ClientAggregatePolicy_GroupVersionKind = CRDGroupVersion.WithKind(ClientAggregatePolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&ClientAggregatePolicy{}, &ClientAggregatePolicyList{})
}
