apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: OptionalClientScopes
metadata:
  annotations:
    meta.upbound.io/example-id: realm/v1alpha1/optionalclientscopes
  labels:
    testing.upbound.io/example-name: optional_scopes
  name: optional-scopes
spec:
  forProvider:
    optionalScopes:
    - address
    - phone
    - offline_access
    - microprofile-jwt
    - ${keycloak_openid_client_scope.client_scope.name}
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientScope
metadata:
  annotations:
    meta.upbound.io/example-id: realm/v1alpha1/optionalclientscopes
  labels:
    testing.upbound.io/example-name: client_scope
  name: client-scope
spec:
  forProvider:
    name: test-client-scope
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: realm/v1alpha1/optionalclientscopes
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm
