apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: allowed-group
spec:
  forProvider:
    name: allowed-group
    realmId: demo
  providerConfigRef:
    name: keycloak-provider-config
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: forbidden-group
spec:
  forProvider:
    name: forbidden-group
    realmId: demo
  providerConfigRef:
    name: keycloak-provider-config
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: allowed-group-roles
spec:
  forProvider:
    groupIdRef:
      name: allowed-group
    roleIdsRefs:
      - name: allowed-role
    realmId: demo
  providerConfigRef:
    name: keycloak-provider-config
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: forbidden-group-roles
spec:
  forProvider:
    groupIdRef:
      name: forbidden-group
    roleIdsRefs:
      - name: forbidden-role
    realmId: demo
  providerConfigRef:
    name: keycloak-provider-config
