apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Memberships
metadata:
  name: allowed-group-members
spec:
  forProvider:
    realmId: demo
    groupIdRef:
      name: allowed-group
    members:
      - alice
  providerConfigRef:
    name: keycloak-provider-config
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Memberships
metadata:
  name: forbidden-group-members
spec:
  forProvider:
    realmId: demo
    groupIdRef:
      name: forbidden-group
    members:
      - bob
  providerConfigRef:
    name: keycloak-provider-config
