apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  name: demo
spec:
  forProvider:
    realm: demo
    enabled: true
    displayName: "Demo Realm"
  providerConfigRef:
    name: keycloak-provider-config
---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: traefik-oidc
spec:
  forProvider:
    clientId: traefik-oidc
    name: traefik-oidc
    realmId: demo
    accessType: CONFIDENTIAL
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    validRedirectUris:
      - "http://localhost:8080/*"
    validPostLogoutRedirectUris:
      - "http://localhost:8080/*"
    webOrigins:
      - "http://localhost:8080"
  writeConnectionSecretToRef:
    name: traefik-oidc-client-secret
    namespace: crossplane-system
  providerConfigRef:
    name: keycloak-provider-config
