apiVersion: client.keycloak.crossplane.io/v1alpha1
kind: ProtocolMapper
metadata:
  name: traefik-roles-mapper
spec:
  forProvider:
    clientIdRef:
      name: traefik-oidc
    realmId: demo
    protocol: openid-connect
    protocolMapper: oidc-usermodel-realm-role-mapper
    name: roles
    config:
      "claim.name": "roles"
      "multivalued": "true"
      "id.token.claim": "true"
      "access.token.claim": "true"
      "userinfo.token.claim": "true"
  providerConfigRef:
    name: keycloak-provider-config
