apiVersion: v1
kind: Namespace
metadata:
  name: example-clientrolepolicy
---
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  name: example-realm
  namespace: example-clientrolepolicy
spec:
  forProvider:
    realm: example-clientrolepolicy
    enabled: true
  providerConfigRef:
    name: keycloak-provider-config
---
apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  name: example-role
  namespace: example-clientrolepolicy
spec:
  forProvider:
    name: example-role
    realmIdRef:
      name: example-realm
  providerConfigRef:
    name: keycloak-provider-config
---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: example-client
  namespace: example-clientrolepolicy
spec:
  forProvider:
    clientId: example-client
    enabled: true
    accessType: CONFIDENTIAL
    serviceAccountsEnabled: true
    realmIdRef:
      name: example-realm
    authorization:
      - policyEnforcementMode: PERMISSIVE
  providerConfigRef:
    name: keycloak-provider-config
---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientRolePolicy
metadata:
  name: example-role-policy
  namespace: example-clientrolepolicy
spec:
  forProvider:
    name: example-role-policy
    type: ROLE
    decisionStrategy: UNANIMOUS
    logic: POSITIVE
    realmIdRef:
      name: example-realm
    resourceServerIdRef:
      name: example-client
    role:
      - required: true
        idRef:
          name: example-role
  providerConfigRef:
    name: keycloak-provider-config
