---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: crossplane-system
  labels: 
    type: provider-credentials
type: Opaque
stringData:
  credentials: |
    {
      "client_id":"admin-cli",
      "username": "admin",
      "password": "admin",
      "url": "http://$KEYCLOAK_IP:$KEYCLOAK_PORT",
      "base_path": "",
      "realm": "master"
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: dev
  labels: 
    type: provider-credentials
type: Opaque
stringData:
  credentials: |
    {
      "client_id":"admin-cli",
      "username": "admin",
      "password": "admin",
      "url": "http://$KEYCLOAK_IP:$KEYCLOAK_PORT",
      "base_path": "",
      "realm": "master"
    }
