apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/user
  labels:
    testing.upbound.io/example-name: user
  name: user
spec:
  forProvider:
    email: bob@domain.com
    enabled: true
    firstName: Bob
    lastName: Bobson
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    username: bob

---

apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/user
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm
