apiVersion: identityprovider.keycloak.crossplane.io/v1alpha1
kind: ImporterIdentityProviderMapper
metadata:
  annotations:
    meta.upbound.io/example-id: identityprovider/v1alpha1/importeridentityprovidermapper
  labels:
    testing.upbound.io/example-name: oidc
  name: oidc
spec:
  forProvider:
    claimName: my-email-claim
    extraConfig:
      syncMode: INHERIT
    identityProviderAlias: my-idp
    name: email-attribute-importer
    realmSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    userAttribute: email

---

apiVersion: oidc.keycloak.crossplane.io/v1alpha1
kind: IdentityProvider
metadata:
  annotations:
    meta.upbound.io/example-id: identityprovider/v1alpha1/importeridentityprovidermapper
  labels:
    testing.upbound.io/example-name: oidc
  name: oidc
spec:
  forProvider:
    alias: oidc
    authorizationUrl: https://example.com/auth
    clientIdSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    defaultScopes: openid random profile
    realmSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    tokenUrl: https://example.com/token

---

apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: identityprovider/v1alpha1/importeridentityprovidermapper
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm
