apiVersion: identityprovider.keycloak.crossplane.io/v1alpha1
kind: KubernetesIdentityProvider
metadata:
  annotations:
    meta.upbound.io/example-id: identityprovider/v1alpha1/kubernetesidentityprovider
  labels:
    testing.upbound.io/example-name: kubernetes
  name: kubernetes
spec:
  forProvider:
    alias: my-k8s-idp
    issuer: https://example.com/issuer/
    realmSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: identityprovider/v1alpha1/kubernetesidentityprovider
  labels:
    testing.upbound.io/example-name: k8s_client
  name: k8s-client
spec:
  forProvider:
    accessType: CONFIDENTIAL
    clientAuthenticatorType: federated-jwt
    clientId: k8s-client
    enabled: true
    extraConfig:
      jwt.credential.issuer: my-k8s-idp
      jwt.credential.sub: system:serviceaccount:<namespace>:<service-account-name>
    name: K8s Client
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    serviceAccountsEnabled: true

---

apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: identityprovider/v1alpha1/kubernetesidentityprovider
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm
