/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type KeystoreJavaKeystoreInitParameters struct {

	// When false, key in not used for signing. Defaults to true.
	// Set if the keys can be used for signing
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// Intended algorithm for the key. Defaults to RS256
	// Intended algorithm for the key
	Algorithm *string `json:"algorithm,omitempty" tf:"algorithm,omitempty"`

	// When false, key is not accessible in this realm. Defaults to true.
	// Set if the keys are enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Alias for the private key.
	// Alias for the private key
	KeyAlias *string `json:"keyAlias,omitempty" tf:"key_alias,omitempty"`

	// Password for the private key.
	// Password for the private key
	KeyPassword *string `json:"keyPassword,omitempty" tf:"key_password,omitempty"`

	// Intended use for the key
	KeyUse *string `json:"keyUse,omitempty" tf:"key_use,omitempty"`

	// Path to keys file on keycloak instance.
	// Path to keys file
	Keystore *string `json:"keystore,omitempty" tf:"keystore,omitempty"`

	// Password for the keys.
	// Password for the keys
	KeystorePassword *string `json:"keystorePassword,omitempty" tf:"keystore_password,omitempty"`

	// Display name of provider when linked in admin console.
	// Display name of provider when linked in admin console.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Priority for the provider. Defaults to 0
	// Priority for the provider
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// The realm this keystore exists in.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/cluster/realm/v1alpha1.Realm
	RealmID *string `json:"realmId,omitempty" tf:"realm_id,omitempty"`

	// Reference to a Realm in realm to populate realmId.
	// +kubebuilder:validation:Optional
	RealmIDRef *v1.Reference `json:"realmIdRef,omitempty" tf:"-"`

	// Selector for a Realm in realm to populate realmId.
	// +kubebuilder:validation:Optional
	RealmIDSelector *v1.Selector `json:"realmIdSelector,omitempty" tf:"-"`
}

type KeystoreJavaKeystoreObservation struct {

	// When false, key in not used for signing. Defaults to true.
	// Set if the keys can be used for signing
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// Intended algorithm for the key. Defaults to RS256
	// Intended algorithm for the key
	Algorithm *string `json:"algorithm,omitempty" tf:"algorithm,omitempty"`

	// When false, key is not accessible in this realm. Defaults to true.
	// Set if the keys are enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Alias for the private key.
	// Alias for the private key
	KeyAlias *string `json:"keyAlias,omitempty" tf:"key_alias,omitempty"`

	// Password for the private key.
	// Password for the private key
	KeyPassword *string `json:"keyPassword,omitempty" tf:"key_password,omitempty"`

	// Intended use for the key
	KeyUse *string `json:"keyUse,omitempty" tf:"key_use,omitempty"`

	// Path to keys file on keycloak instance.
	// Path to keys file
	Keystore *string `json:"keystore,omitempty" tf:"keystore,omitempty"`

	// Password for the keys.
	// Password for the keys
	KeystorePassword *string `json:"keystorePassword,omitempty" tf:"keystore_password,omitempty"`

	// Display name of provider when linked in admin console.
	// Display name of provider when linked in admin console.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// Priority for the provider. Defaults to 0
	// Priority for the provider
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// The realm this keystore exists in.
	RealmID *string `json:"realmId,omitempty" tf:"realm_id,omitempty"`
}

type KeystoreJavaKeystoreParameters struct {

	// When false, key in not used for signing. Defaults to true.
	// Set if the keys can be used for signing
	// +kubebuilder:validation:Optional
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// Intended algorithm for the key. Defaults to RS256
	// Intended algorithm for the key
	// +kubebuilder:validation:Optional
	Algorithm *string `json:"algorithm,omitempty" tf:"algorithm,omitempty"`

	// When false, key is not accessible in this realm. Defaults to true.
	// Set if the keys are enabled
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Alias for the private key.
	// Alias for the private key
	// +kubebuilder:validation:Optional
	KeyAlias *string `json:"keyAlias,omitempty" tf:"key_alias,omitempty"`

	// Password for the private key.
	// Password for the private key
	// +kubebuilder:validation:Optional
	KeyPassword *string `json:"keyPassword,omitempty" tf:"key_password,omitempty"`

	// Intended use for the key
	// +kubebuilder:validation:Optional
	KeyUse *string `json:"keyUse,omitempty" tf:"key_use,omitempty"`

	// Path to keys file on keycloak instance.
	// Path to keys file
	// +kubebuilder:validation:Optional
	Keystore *string `json:"keystore,omitempty" tf:"keystore,omitempty"`

	// Password for the keys.
	// Password for the keys
	// +kubebuilder:validation:Optional
	KeystorePassword *string `json:"keystorePassword,omitempty" tf:"keystore_password,omitempty"`

	// Display name of provider when linked in admin console.
	// Display name of provider when linked in admin console.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Priority for the provider. Defaults to 0
	// Priority for the provider
	// +kubebuilder:validation:Optional
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// The realm this keystore exists in.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-keycloak/apis/cluster/realm/v1alpha1.Realm
	// +kubebuilder:validation:Optional
	RealmID *string `json:"realmId,omitempty" tf:"realm_id,omitempty"`

	// Reference to a Realm in realm to populate realmId.
	// +kubebuilder:validation:Optional
	RealmIDRef *v1.Reference `json:"realmIdRef,omitempty" tf:"-"`

	// Selector for a Realm in realm to populate realmId.
	// +kubebuilder:validation:Optional
	RealmIDSelector *v1.Selector `json:"realmIdSelector,omitempty" tf:"-"`
}

// KeystoreJavaKeystoreSpec defines the desired state of KeystoreJavaKeystore
type KeystoreJavaKeystoreSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     KeystoreJavaKeystoreParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider KeystoreJavaKeystoreInitParameters `json:"initProvider,omitempty"`
}

// KeystoreJavaKeystoreStatus defines the observed state of KeystoreJavaKeystore.
type KeystoreJavaKeystoreStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        KeystoreJavaKeystoreObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// KeystoreJavaKeystore is the Schema for the KeystoreJavaKeystores API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,keycloak}
type KeystoreJavaKeystore struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.keyAlias) || (has(self.initProvider) && has(self.initProvider.keyAlias))",message="spec.forProvider.keyAlias is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.keyPassword) || (has(self.initProvider) && has(self.initProvider.keyPassword))",message="spec.forProvider.keyPassword is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.keystore) || (has(self.initProvider) && has(self.initProvider.keystore))",message="spec.forProvider.keystore is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.keystorePassword) || (has(self.initProvider) && has(self.initProvider.keystorePassword))",message="spec.forProvider.keystorePassword is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   KeystoreJavaKeystoreSpec   `json:"spec"`
	Status KeystoreJavaKeystoreStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KeystoreJavaKeystoreList contains a list of KeystoreJavaKeystores
type KeystoreJavaKeystoreList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KeystoreJavaKeystore `json:"items"`
}

// Repository type metadata.
var (
	KeystoreJavaKeystore_Kind             = "KeystoreJavaKeystore"
	KeystoreJavaKeystore_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: KeystoreJavaKeystore_Kind}.String()
	KeystoreJavaKeystore_KindAPIVersion   = KeystoreJavaKeystore_Kind + "." + CRDGroupVersion.String()
	KeystoreJavaKeystore_GroupVersionKind = CRDGroupVersion.WithKind(KeystoreJavaKeystore_Kind)
)

func init() {
	SchemeBuilder.Register(&KeystoreJavaKeystore{}, &KeystoreJavaKeystoreList{})
}
