# Example: Realm RSA Generated Encryption Keystore
# This example demonstrates how to let Keycloak generate an RSA key pair that
# is used for encryption (e.g. encrypted ID tokens or request objects).
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: KeystoreRsaEncGenerated
metadata:
  name: rsa-enc-generated-keystore
spec:
  forProvider:
    realmIdRef:
      name: basic-realm  # Reference to the Realm resource
    name: crossplane-rsa-enc-generated-key
    active: true
    enabled: true
    priority: 100
    algorithm: RSA-OAEP  # e.g. 'RSA-OAEP', 'RSA-OAEP-256', 'RSA1_5'
    keySize: 2048
  providerConfigRef:
    name: "keycloak-provider-config"  # Reference to the ProviderConfig resource
