apiVersion: samlclient.keycloak.m.crossplane.io/v1alpha1
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: samlclient/v1alpha1/client
  labels:
    testing.upbound.io/example-name: saml_client
  name: saml-client
  namespace: upbound-system
spec:
  forProvider:
    clientId: saml-client
    includeAuthnStatement: true
    name: saml-client
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    signAssertions: true
    signDocuments: false
    signingCertificateSecretRef:
      key: attribute.saml-cert.pem
      name: example-secret
    signingPrivateKeySecretRef:
      key: attribute.saml-key.pem
      name: example-secret

---

apiVersion: realm.keycloak.m.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: samlclient/v1alpha1/client
  labels:
    testing.upbound.io/example-name: realm
  name: realm
  namespace: upbound-system
spec:
  forProvider:
    enabled: true
    realm: my-realm
