# Example 1: Basic Realm Configuration
# This example demonstrates the minimum required fields to create a realm.
apiVersion: organization.keycloak.crossplane.io/v1alpha1
kind: Organization
metadata:
  name: example
spec:
  deletionPolicy: Delete
  forProvider:
    realm: "orgs"  # The name of the realm in Keycloak
    name: example
    enabled: true
    domain:
      - name: example.com
      - name: example.org
  providerConfigRef:
    name: "keycloak-provider-config"  # Reference to the ProviderConfig resource
