---
# Example 1: Basic User
# This is a basic user with the minimum required fields.
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: example-user
spec:
  deletionPolicy: Delete
  forProvider:
    realmId: "orgs"  # The realm to which this user belongs
    username: "example-user"     # The username for this user
    email: user@example.com
  providerConfigRef:
    name: "keycloak-provider-config"  # Reference to the provider configuration
