apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: role/v1alpha1/role
  labels:
    testing.upbound.io/example-name: realm_role
  name: realm-role
spec:
  forProvider:
    attributes:
      key: value
      multivalue: value1##value2
    description: My Realm Role
    name: my-realm-role
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: role/v1alpha1/role
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm
