apiVersion: defaults.keycloak.crossplane.io/v1alpha1
kind: DefaultGroups
metadata:
  annotations:
    meta.upbound.io/example-id: defaults/v1alpha1/defaultgroups
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    groupIdsRefs:
    - name: group
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: defaults/v1alpha1/defaultgroups
  labels:
    testing.upbound.io/example-name: group
  name: group
spec:
  forProvider:
    name: my-group
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: defaults/v1alpha1/defaultgroups
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm
