apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: v1
data:
  KC_BOOTSTRAP_ADMIN_PASSWORD: admin
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  KC_HOSTNAME: http://localhost:8080
  KC_LOG_LEVEL: info
kind: ConfigMap
metadata:
  labels:
    app: keycloak
  name: keycloak-cm
  namespace: keycloak
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    await: service
  labels:
    app: keycloak
  name: kc
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
        app.kubernetes.io/name: keycloak
    spec:
      containers:
      - args:
        - start-dev
        envFrom:
        - configMapRef:
            name: keycloak-cm
        image: quay.io/keycloak/keycloak:26.0.2
        name: keycloak
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 500Mi
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 6
