---
# AES Generated keystore
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: RealmKeystoreAesGenerated
metadata:
  name: aes-keystore
spec:
  forProvider:
    name: aes-generated
    priority: 100
    realmRef:
      name: "dev"
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"

---
# ECDSA Generated keystore
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: RealmKeystoreEcdsaGenerated
metadata:
  name: ecdsa-keystore
spec:
  forProvider:
    name: ecdsa-generated
    priority: 100
    realmRef:
      name: "dev"
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"

---
# HMAC Generated keystore
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: RealmKeystoreHmacGenerated
metadata:
  name: hmac-keystore
spec:
  forProvider:
    name: hmac-generated
    priority: 100
    realmRef:
      name: "dev"
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"

---
# RSA Generated keystore (in addition to 004-realm-keystore-rsa.yaml)
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: RealmKeystoreRsaGenerated
metadata:
  name: rsa-generated-keystore
spec:
  forProvider:
    name: rsa-generated
    priority: 100
    realmRef:
      name: "dev"
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"

---
# Java Keystore
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: RealmKeystoreJavaKeystore
metadata:
  name: java-keystore
spec:
  forProvider:
    name: java-keystore
    priority: 100
    realmRef:
      name: "dev"
      policy:
        resolve: Always
    keystorePasswordSecretRef:
      key: password
      name: keystore-secret
  providerConfigRef:
    name: "keycloak-provider-config"
