---
# AES Generated keystore
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: RealmKeystoreAesGenerated
metadata:
  name: aes-keystore
spec:
  forProvider:
    active: true
    enabled: true
    name: crossplane-aes-key
    priority: 100
    secretSize: 16
    realmIdRef:
      name: "dev"
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"

---
# ECDSA Generated keystore
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: RealmKeystoreEcdsaGenerated
metadata:
  name: ecdsa-keystore
spec:
  forProvider:
    active: true
    ellipticCurveKey: P-256
    enabled: true
    name: crossplane-ecdsa-key
    priority: 100
    realmIdRef:
      name: "dev"
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"

---
# HMAC Generated keystore
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: RealmKeystoreHmacGenerated
metadata:
  name: hmac-keystore
spec:
  forProvider:
    active: true
    algorithm: HS256
    enabled: true
    name: crossplane-hmac-key
    priority: 100
    secretSize: 64
    realmIdRef:
      name: "dev"
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"

---
# RSA Generated keystore
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: RealmKeystoreRsaGenerated
metadata:
  name: rsa-generated-keystore
spec:
  forProvider:
    active: true
    algorithm: RS256
    enabled: true
    keySize: 2048
    name: crossplane-rsa-generated-key
    priority: 100
    realmIdRef:
      name: "dev"
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"
