apiVersion: identityprovider.keycloak.crossplane.io/v1alpha1
kind: ProviderTokenExchangeScopePermission
metadata:
  name: token-exchange-permission
spec:
  forProvider:
    clientsRefs:
    - name: webapp-client
    policyType: client
    providerAliasRef:
      name: oidc-identity-provider
    realmIdRef:
      name: "dev-realm"
  providerConfigRef:
    name: "keycloak-provider-config"
