apiVersion: oidc.keycloak.crossplane.io/v1alpha1
kind: GithubIdentityProvider
metadata:
  name: github
spec:
  forProvider:
    alias: github
    clientIdSecretRef:
      key: client-id
      name: client-secret
      namespace: dev
    clientSecretSecretRef:
      key: client-secret
      name: client-secret
      namespace: dev
    realmRef:
      name: "dev"
      policy:
        resolve: Always
    syncMode: IMPORT
    trustEmail: true
  providerConfigRef:
    name: "keycloak-provider-config"
