---
# Importer mapper - imports IdP claim into user attribute
apiVersion: identityprovider.keycloak.crossplane.io/v1alpha1
kind: ImporterIdentityProviderMapper
metadata:
  name: import-email-attribute
spec:
  forProvider:
    claimName: email
    extraConfig:
      syncMode: INHERIT
    identityProviderAlias: my-idp
    name: import-email-from-idp
    realmRef:
      name: "dev"
      policy:
        resolve: Always
    userAttribute: email
  providerConfigRef:
    name: "keycloak-provider-config"

---
# To role mapper - maps IdP claim/value to a realm role
apiVersion: identityprovider.keycloak.crossplane.io/v1alpha1
kind: ToRoleIdentityProviderMapper
metadata:
  name: map-idp-attribute-to-role
spec:
  forProvider:
    claimName: role
    claimValue: admin
    extraConfig:
      syncMode: INHERIT
    identityProviderAlias: my-idp
    name: map-attribute-admin-to-role
    realmRef:
      name: "dev"
      policy:
        resolve: Always
    role: test
  providerConfigRef:
    name: "keycloak-provider-config"

---
# Attribute mapper - adds hardcoded attribute
apiVersion: identityprovider.keycloak.crossplane.io/v1alpha1
kind: AttributeIdentityProviderMapper
metadata:
  name: hardcode-department-attribute
spec:
  forProvider:
    attributeName: department
    attributeValue: engineering
    extraConfig:
      syncMode: INHERIT
    identityProviderAlias: my-idp
    name: hardcode-department
    realmRef:
      name: "dev"
      policy:
        resolve: Always
    userSession: true
  providerConfigRef:
    name: "keycloak-provider-config"

---
# Group mapper - assigns users to an existing group
apiVersion: identityprovider.keycloak.crossplane.io/v1alpha1
kind: GroupIdentityProviderMapper
metadata:
  name: assign-employees-group
spec:
  forProvider:
    extraConfig:
      syncMode: INHERIT
    group: test
    identityProviderAlias: my-idp
    name: assign-to-test-group
    realmRef:
      name: "dev"
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"

---
# Role mapper - assigns an existing realm role
apiVersion: identityprovider.keycloak.crossplane.io/v1alpha1
kind: RoleIdentityProviderMapper
metadata:
  name: hardcode-user-role
spec:
  forProvider:
    extraConfig:
      syncMode: INHERIT
    identityProviderAlias: my-idp
    name: hardcode-user-role
    realmRef:
      name: "dev"
      policy:
        resolve: Always
    role: test
  providerConfigRef:
    name: "keycloak-provider-config"

---
# User template importer - imports user data using template
apiVersion: identityprovider.keycloak.crossplane.io/v1alpha1
kind: TemplateImporterIdentityProviderMapper
metadata:
  name: import-user-template
spec:
  forProvider:
    extraConfig:
      syncMode: INHERIT
    identityProviderAlias: my-idp
    name: import-user-template
    realmRef:
      name: "dev"
      policy:
        resolve: Always
    template: "user.${CLAIM.sub}"
  providerConfigRef:
    name: "keycloak-provider-config"
