# This test case demonstrates issue #163 fix: Execution resources can now reference Subflow resources
# using parentSubflowAliasRef and parentSubflowAliasSelector
apiVersion: authenticationflow.keycloak.crossplane.io/v1alpha1
kind: Execution
metadata:
  name: execution-in-subflow-ref
  labels:
    test-type: subflow-reference
spec:
  deletionPolicy: Delete
  forProvider:
    authenticator: auth-username-password-form
    # NEW: Using parentSubflowAliasRef to reference a Subflow resource
    parentSubflowAliasRef:
      name: subflow
    realmIdRef:
      name: "dev"
      policy:
        resolve: Always
    requirement: REQUIRED
  providerConfigRef:
    name: "keycloak-provider-config"
---
apiVersion: authenticationflow.keycloak.crossplane.io/v1alpha1
kind: Execution
metadata:
  name: execution-in-subflow-selector
  labels:
    test-type: subflow-reference
spec:
  deletionPolicy: Delete
  forProvider:
    authenticator: auth-otp-form
    # NEW: Using parentSubflowAliasSelector to reference a Subflow resource by labels
    parentSubflowAliasSelector:
      matchLabels:
        subflow-type: test-subflow
    realmIdRef:
      name: "dev"
      policy:
        resolve: Always
    requirement: REQUIRED
  providerConfigRef:
    name: "keycloak-provider-config"
