apiVersion: defaults.keycloak.crossplane.io/v1alpha1
kind: DefaultGroups
metadata:
  name: my-default-groups
spec:
  deletionPolicy: Delete
  forProvider:
    groupIdsRefs:
      - name: test
        policy:
          resolve: Always
    realmIdRef:
      name: "dev"
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"
