apiVersion: defaults.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: default-roles
spec:
  deletionPolicy: Delete
  forProvider:
    defaultRolesRefs:
      - name: test
        policy:
          resolve: Always
    realmIdRef:
      name: "dev"
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"
