apiVersion: ldap.keycloak.crossplane.io/v1alpha1
kind: GroupMapper
metadata:
  name: ldap-group-mapper
spec:
  deletionPolicy: Delete
  forProvider:
    groupNameLdapAttribute: cn
    groupObjectClasses:
      - groupOfNames
    ldapGroupsDn: dc=example,dc=org
    ldapUserFederationIdRef:
      name: ldap-user-federation
      policy:
        resolve: Always
    memberofLdapAttribute: memberOf
    membershipAttributeType: DN
    membershipLdapAttribute: member
    membershipUserLdapAttribute: cn
    name: group-mapper
    realmIdRef:
      name: "dev"
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"
---
apiVersion: ldap.keycloak.crossplane.io/v1alpha1
kind: HardcodedGroupMapper
metadata:
  name: assign-group-to-users
spec:
  deletionPolicy: Delete
  forProvider:
    groupRef:
      name: test
    ldapUserFederationIdRef:
      name: ldap-user-federation
      policy:
        resolve: Always
    name: assign-group-to-users
    realmIdRef:
      name: "dev"
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"
---
