apiVersion: samlclient.keycloak.crossplane.io/v1alpha1
kind: UserPropertyProtocolMapper
metadata:
  annotations:
    meta.upbound.io/example-id: samlclient/v1alpha1/userpropertyprotocolmapper
  labels:
    testing.upbound.io/example-name: saml_user_property_mapper
  name: saml-user-property-mapper
spec:
  forProvider:
    clientIdSelector:
      matchLabels:
        testing.upbound.io/example-name: saml_client
    name: email-user-property-mapper
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    samlAttributeName: email
    samlAttributeNameFormat: Unspecified
    userProperty: email

---

apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: samlclient/v1alpha1/userpropertyprotocolmapper
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm

---

apiVersion: samlclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: samlclient/v1alpha1/userpropertyprotocolmapper
  labels:
    testing.upbound.io/example-name: saml_client
  name: saml-client
spec:
  forProvider:
    clientId: saml-client
    name: saml-client
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
