apiVersion: realm.keycloak.m.crossplane.io/v1alpha1
kind: KeystoreRsa
metadata:
  name: keystore-rsa
  namespace: dev-ns
spec:
  forProvider:
    active: true
    algorithm: RS256
    certificateSecretRef:
      key: cert
      name: rsa-key
    enabled: true
    name: my-rsa-key
    priority: 100
    privateKeySecretRef:
      key: priv
      name: rsa-key
    providerId: rsa
    realmIdRef:
      name: "dev-ns"
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config" # Reference to the ProviderConfig resource
    kind: ProviderConfig
