---
# AES Generated keystore (namespaced)
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: RealmKeystoreAesGenerated
metadata:
  name: aes-keystore
  namespace: dev-ns
spec:
  forProvider:
    name: aes-generated
    priority: 100
    realmRef:
      name: "dev"
      namespace: dev-ns
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"
    namespace: dev-ns

---
# ECDSA Generated keystore (namespaced)
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: RealmKeystoreEcdsaGenerated
metadata:
  name: ecdsa-keystore
  namespace: dev-ns
spec:
  forProvider:
    name: ecdsa-generated
    priority: 100
    realmRef:
      name: "dev"
      namespace: dev-ns
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"
    namespace: dev-ns

---
# HMAC Generated keystore (namespaced)
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: RealmKeystoreHmacGenerated
metadata:
  name: hmac-keystore
  namespace: dev-ns
spec:
  forProvider:
    name: hmac-generated
    priority: 100
    realmRef:
      name: "dev"
      namespace: dev-ns
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"
    namespace: dev-ns

---
# RSA Generated keystore (namespaced)
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: RealmKeystoreRsaGenerated
metadata:
  name: rsa-generated-keystore
  namespace: dev-ns
spec:
  forProvider:
    name: rsa-generated
    priority: 100
    realmRef:
      name: "dev"
      namespace: dev-ns
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"
    namespace: dev-ns

---
# Java Keystore (namespaced)
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: RealmKeystoreJavaKeystore
metadata:
  name: java-keystore
  namespace: dev-ns
spec:
  forProvider:
    name: java-keystore
    priority: 100
    realmRef:
      name: "dev"
      namespace: dev-ns
      policy:
        resolve: Always
    keystorePasswordSecretRef:
      key: password
      name: keystore-secret
      namespace: dev-ns
  providerConfigRef:
    name: "keycloak-provider-config"
    namespace: dev-ns
