---
# AES Generated keystore (namespaced)
apiVersion: realm.keycloak.m.crossplane.io/v1alpha1
kind: RealmKeystoreAesGenerated
metadata:
  name: aes-keystore
  namespace: dev-ns
spec:
  forProvider:
    name: aes-generated
    priority: 100
    realmIdRef:
      name: "dev-ns"
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig

---
# ECDSA Generated keystore (namespaced)
apiVersion: realm.keycloak.m.crossplane.io/v1alpha1
kind: RealmKeystoreEcdsaGenerated
metadata:
  name: ecdsa-keystore
  namespace: dev-ns
spec:
  forProvider:
    name: ecdsa-generated
    priority: 100
    realmIdRef:
      name: "dev-ns"
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig

---
# HMAC Generated keystore (namespaced)
apiVersion: realm.keycloak.m.crossplane.io/v1alpha1
kind: RealmKeystoreHmacGenerated
metadata:
  name: hmac-keystore
  namespace: dev-ns
spec:
  forProvider:
    name: hmac-generated
    priority: 100
    realmIdRef:
      name: "dev-ns"
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig

---
# RSA Generated keystore (namespaced)
apiVersion: realm.keycloak.m.crossplane.io/v1alpha1
kind: RealmKeystoreRsaGenerated
metadata:
  name: rsa-generated-keystore
  namespace: dev-ns
spec:
  forProvider:
    name: rsa-generated
    priority: 100
    realmIdRef:
      name: "dev-ns"
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig
