---
# AES Generated keystore (namespaced)
apiVersion: realm.keycloak.m.crossplane.io/v1alpha1
kind: KeystoreAesGenerated
metadata:
  name: aes-keystore
  namespace: dev-ns
spec:
  forProvider:
    active: true
    enabled: true
    name: crossplane-aes-key
    priority: 100
    secretSize: 16
    realmId: "dev-ns"
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig

---
# ECDSA Generated keystore (namespaced)
apiVersion: realm.keycloak.m.crossplane.io/v1alpha1
kind: KeystoreEcdsaGenerated
metadata:
  name: ecdsa-keystore
  namespace: dev-ns
spec:
  forProvider:
    active: true
    ellipticCurveKey: P-256
    enabled: true
    name: crossplane-ecdsa-key
    priority: 100
    realmId: "dev-ns"
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig

---
# HMAC Generated keystore (namespaced)
apiVersion: realm.keycloak.m.crossplane.io/v1alpha1
kind: KeystoreHMACGenerated
metadata:
  name: hmac-keystore
  namespace: dev-ns
spec:
  forProvider:
    active: true
    algorithm: HS256
    enabled: true
    name: crossplane-hmac-key
    priority: 100
    secretSize: 64
    realmId: "dev-ns"
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig

---
# RSA Generated keystore (namespaced)
apiVersion: realm.keycloak.m.crossplane.io/v1alpha1
kind: KeystoreRsaGenerated
metadata:
  name: rsa-generated-keystore
  namespace: dev-ns
spec:
  forProvider:
    active: true
    algorithm: RS256
    enabled: true
    keySize: 2048
    name: crossplane-rsa-generated-key
    priority: 100
    realmId: "dev-ns"
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig

