apiVersion: realm.keycloak.m.crossplane.io/v1alpha1
kind: ClientPolicyProfile
metadata:
  name: client-policy-profile
  namespace: dev-ns
spec:
  forProvider:
    executor:
      - configuration:
          auto-configure: "true"
        name: intent-client-bind-checker
      - name: secure-session
    name: my-profile
    realmIdRef:
      name: "dev-ns"
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig
