---
# E2E test for child groups with the same name under different parents.
# Regression test for https://github.com/crossplane-contrib/provider-keycloak/issues/542
apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Group
metadata:
  name: test-parent-1
  namespace: dev-ns
  labels:
    role: parent
    parent: test1
spec:
  forProvider:
    name: test-parent-1
    realmId: dev-ns
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig
---
apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Group
metadata:
  name: test-parent-2
  namespace: dev-ns
  labels:
    role: parent
    parent: test2
spec:
  forProvider:
    name: test-parent-2
    realmId: dev-ns
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig
---
apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Group
metadata:
  name: test-child-1
  namespace: dev-ns
spec:
  forProvider:
    name: test-child
    realmId: dev-ns
    parentIdSelector:
      matchLabels:
        role: parent
        parent: test1
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig
---
apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Group
metadata:
  name: test-child-2
  namespace: dev-ns
spec:
  forProvider:
    name: test-child
    realmId: dev-ns
    parentIdSelector:
      matchLabels:
        role: parent
        parent: test2
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig
