apiVersion: user.keycloak.m.crossplane.io/v1alpha1
kind: Groups
metadata:
  name: user-groups
  namespace: dev-ns
spec:
  forProvider:
    realmIdRef:
      name: "dev-ns"
      policy:
        resolve: Always
    groupIdsRefs:
      - name: test
        policy:
          resolve: Always
    userIdRef:
      name: "tim-tester"
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig
