apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: group-roles
  namespace: dev-ns
spec:
  forProvider:
    realmIdRef:
      name: "dev-ns"
      policy:
        resolve: Always
    groupIdRef:
      name: test
      policy:
        resolve: Always
    roleIdsRefs:
      - name: "test-client"
        policy:
          resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig
