apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Permissions
metadata:
  name: my-group-permission
  namespace: dev-ns
spec:
  # Fixme: Delete will result in realm not found exception
  managementPolicies: ["Create", "Update", "Observe"]
  forProvider:
    realmIdRef:
      name: "dev-ns"
      policy:
        resolve: Always
    groupIdRef:
      name: "test"
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig
