apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientPermissions
metadata:
  name: my-permission
  namespace: dev-ns
spec:
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig
  forProvider:
    clientIdRef:
      name: "test"
      policy:
        resolve: Always
    realmIdRef:
      name: "dev-ns"
      policy:
        resolve: Always

