---
apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientServiceAccountRealmRole
metadata:
  name: service-account-realm-role
  namespace: dev-ns
spec:
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig
  forProvider:
    realmIdRef:
      name: "dev-ns"
    role: "svc-realm-role"
    serviceAccountUserClientIdRef:
      name: "service-acc-1"
---
apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientServiceAccountRole
metadata:
  name: service-account-role
  namespace: dev-ns
spec:
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig
  forProvider:
    clientIdRef:
      name: "test"
    realmIdRef:
      name: "dev-ns"
    roleRef:
      name: "svc-role"
    serviceAccountUserClientIdRef:
      name: "service-acc-1"
---
apiVersion: role.keycloak.m.crossplane.io/v1alpha1
kind: Role
metadata:
  name: svc-realm-role
  namespace: dev-ns
spec:
  forProvider:
    realmId: "dev-ns"
    name: "svc-realm-role"
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig