apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: ClientClientPolicy
metadata:
  name: my-client-policy
  namespace: dev-ns
spec:
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig
  forProvider:
    name: my-client-policy
    clientsRefs:
      - name: "test"
    decisionStrategy: UNANIMOUS
    logic: POSITIVE
    resourceServerIdRef:
      name: "test"
    realmIdRef:
      name: "dev-ns"
