---
apiVersion: samlclient.keycloak.m.crossplane.io/v1alpha1
kind: Client
metadata:
  name: saml-client
  namespace: dev-ns
spec:
  forProvider:
    clientId: saml-client-id
    includeAuthnStatement: true
    name: saml-client
    realmIdRef:
      name: "dev-ns"
      policy:
        resolve: Always
    signAssertions: true
    signDocuments: false
    signingCertificateSecretRef:
      name: rsa-key
      key: cert
    signingPrivateKeySecretRef:
      name: saml-cliet-cert
      key: priv
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig
---
apiVersion: client.keycloak.m.crossplane.io/v1alpha1
kind: ProtocolMapper
metadata:
  name: saml-client-protocol-mapper
  namespace: dev-ns
spec:
  providerConfigRef:
    kind: ProviderConfig
    name: "keycloak-provider-config"
  forProvider:
    name: "user roles"
    protocol: "saml"
    samlClientIdRef:
      name: "saml-client"
    realmIdRef:
      name: "dev-ns"
      policy:
        resolve: Always
    protocolMapper: "saml-role-list-mapper"
    config:
      attribute.name: "Role"
      attribute.nameformat: "Basic"
      friendly.name: "test"
      single: "true"