apiVersion: defaults.keycloak.m.crossplane.io/v1alpha1
kind: DefaultGroups
metadata:
  name: my-default-groups
  namespace: dev-ns
spec:
  forProvider:
    groupIdsRefs:
      - name: test
    realmIdRef:
      name: "dev-ns"
      policy:
        resolve: Always
  providerConfigRef:
    name: "keycloak-provider-config"
    kind: ProviderConfig
