apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: crossplane-system
  labels:
    type: provider-credentials
type: Opaque
stringData: # these have to be in a credentials json when used with the xrd XBuiltinObjects
  credentials: |
    {
      "client_id": "crossplane",
      "client_secret": "xppw_OJKzQjuBoyPlIEePgiWg",
      "url": "http://keycloak.keycloak.svc.cluster.local",
      "realm": "master"
    }
---
apiVersion: keycloak.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: keycloak-config
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      name: keycloak-credentials
      key: credentials
      namespace: crossplane-system