apiVersion: default.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  annotations:
    meta.upbound.io/example-id: default/v1alpha1/roles
  labels:
    testing.upbound.io/example-name: default_roles
  name: default-roles
spec:
  forProvider:
    defaultRoles:
    - uma_authorization
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: default/v1alpha1/roles
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm
