apiVersion: openidgroup.keycloak.m.crossplane.io/v1alpha1
kind: GroupMembershipProtocolMapper
metadata:
  annotations:
    meta.upbound.io/example-id: openidgroup/v1alpha1/groupmembershipprotocolmapper
  labels:
    testing.upbound.io/example-name: group_membership_mapper
  name: group-membership-mapper
  namespace: upbound-system
spec:
  forProvider:
    claimName: groups
    clientIdSelector:
      matchLabels:
        testing.upbound.io/example-name: openid_client
    name: group-membership-mapper
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: openidgroup/v1alpha1/groupmembershipprotocolmapper
  labels:
    testing.upbound.io/example-name: openid_client
  name: openid-client
  namespace: upbound-system
spec:
  forProvider:
    accessType: CONFIDENTIAL
    clientId: client
    enabled: true
    name: client
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    validRedirectUris:
    - http://localhost:8080/openid-callback

---

apiVersion: realm.keycloak.m.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: openidgroup/v1alpha1/groupmembershipprotocolmapper
  labels:
    testing.upbound.io/example-name: realm
  name: realm
  namespace: upbound-system
spec:
  forProvider:
    enabled: true
    realm: my-realm
