/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *FacebookIdentityProvider) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GithubIdentityProvider) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GoogleIdentityProvider) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IdentityProvider) Hub() {}
