name: Deploy Docs PR Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - 'docs/**'

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        if: github.event.action != 'closed'
        with:
          go-version: '1.26.x'

      - name: Setup Hugo
        if: github.event.action != 'closed'
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.150.0'
          extended: true

      - name: Build documentation (PR preview)
        if: github.event.action != 'closed'
        working-directory: docs
        env:
          GOTOOLCHAIN: local
        run: hugo --minify --baseURL "https://crossplane-contrib.github.io/provider-keycloak/pr-preview/pr-${{ github.event.pull_request.number }}/"

      - name: Deploy PR preview
        uses: rossjrw/pr-preview-action@ffa7509e91a3ec8dfc2e5536c4d5c1acdf7a6de9 # v1
        with:
          source-dir: docs/public
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
