apiVersion: client.keycloak.m.crossplane.io/v1alpha1
kind: ProtocolMapper
metadata:
  annotations:
    meta.upbound.io/example-id: client/v1alpha1/protocolmapper
  labels:
    testing.upbound.io/example-name: saml_hardcode_attribute_mapper
  name: saml-hardcode-attribute-mapper
  namespace: upbound-system
spec:
  forProvider:
    clientIdSelector:
      matchLabels:
        testing.upbound.io/example-name: saml_client
    config:
      attribute.name: name
      attribute.nameformat: Basic
      attribute.value: value
      friendly.name: display name
    name: test-mapper
    protocol: saml
    protocolMapper: saml-hardcode-attribute-mapper
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: realm.keycloak.m.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: client/v1alpha1/protocolmapper
  labels:
    testing.upbound.io/example-name: realm
  name: realm
  namespace: upbound-system
spec:
  forProvider:
    enabled: true
    realm: my-realm

---

apiVersion: samlclient.keycloak.m.crossplane.io/v1alpha1
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: client/v1alpha1/protocolmapper
  labels:
    testing.upbound.io/example-name: saml_client
  name: saml-client
  namespace: upbound-system
spec:
  forProvider:
    clientId: test-client
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
